services:
  busadmin:
    image: "pavan6458/busadmin:v1"
    container_name: busadmin-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
  buspassengers:
    image: "pavan6458/busschedule:v1"
    container_name: buspassengers-ms
    ports:
      - "8084:8084"
    deploy:
      resources:
        limits:
          memory: 700m
  busschedule:
    image: "pavan6458/busschedule:v1"
    container_name: busschedule-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
  usermaster:
    image: "pavan6458/usermaster:v1"
    container_name: usermaster-ms
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
