version: '3.3'

services:
  eurekaserver:
    container_name: eurekaserver
    build: ./Bus-ms-eureka-server
    image: eurekaserver:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/BusBooking
      SPRING_DATASOURCE_USERNAME: BusBooking
      SPRING_DATASOURCE_PASSWORD: Admin123
    ports:
      - "8070:8070"
    networks:
      - busservices
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  configserver:
    container_name: configserver-ms
    build: ./Bus-ms-config-Server
    image: configserver:latest

    ports:
      - "8071:8071"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/BusBooking
      SPRING_DATASOURCE_USERNAME: BusBooking
      SPRING_DATASOURCE_PASSWORD: Admin123
    networks:
      - busservices
    depends_on:
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 700m

  busadmin:
    container_name: busadmin-ms
    build: ./Bus-ms-Admin
    image: busadmin:latest
    ports:
      - "8086:8086"
    networks:
      - busservices
    environment:
      SPRING_APPLICATION_NAME: busadmin
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/BusBooking
      SPRING_DATASOURCE_USERNAME: BusBooking
      SPRING_DATASOURCE_PASSWORD: Admin123
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  busschedule:
    container_name: busschedule-ms
    build: ./Bus-ms-schedule
    image: busschedule:latest
    ports:
      - "8083:8083"
    networks:
      - busservices
    environment:
      SPRING_APPLICATION_NAME: busschedule
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/BusBooking
      SPRING_DATASOURCE_USERNAME: BusBooking
      SPRING_DATASOURCE_PASSWORD: Admin123
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  buspassengers:
    container_name: buspassangers-ms
    build: ./Bus-ms-passangers
    image: buspassengers:latest
    ports:
      - "8082:8082"
    networks:
      - busservices
    environment:
      SPRING_APPLICATION_NAME: buspassengers
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/BusBooking
      SPRING_DATASOURCE_USERNAME: BusBooking
      SPRING_DATASOURCE_PASSWORD: Admin123
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  usermaster:
    container_name: usermaster-ms
    build: ./Bus-ms-Users
    image: usermaster:latest
    ports:
      - "8084:8084"
    networks:
      - busservices
    environment:
      SPRING_APPLICATION_NAME: usermaster
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/BusBooking
      SPRING_DATASOURCE_USERNAME: BusBooking
      SPRING_DATASOURCE_PASSWORD: Admin123
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

  gateway:
   container_name: gateway-ms
   build: ./gatewayServer
   image: gateway:latest
   ports:
    - "8085:8084"   # Host:Container
   networks:
    - busservices
   depends_on:
    eurekaserver:
      condition: service_healthy
    configserver:
      condition: service_healthy
    busadmin:
      condition: service_healthy
    usermaster:
      condition: service_healthy
    buspassengers:
      condition: service_healthy
    busschedule:
      condition: service_healthy
   environment:
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
   deploy:
    resources:
      limits:
        memory: 700m
   healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s


networks:
  busservices:
    driver: bridge
