
Spring:
  application:
    name: "api_gateway"
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
server:
  port: 8002

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000


