spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BusBooking
    username: BusBooking
    password: Admin123
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  profiles:
    active: default



  config:
    import: optional:configserver:http://localhost:8071

  application:
    name: buspassengers

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  resources:
    static-locations: file:src/main/resources/static/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8082

build:
  version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "bus passangers"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"
