server:
  port: 8070

spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071"

eureka:
  instance:
    hostname: "eurekaserver"
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,readiness,liveness
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
