spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BusBooking
    username: BusBooking
    password: Admin123
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true


  profiles:
    active: "qa"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  config:
    import: "optional:configserver:http://localhost:8071"

  application:
    name: busschedule

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update




server:
  port: 8083

build:
  version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

endpoints:
  shutdown:
    enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "bus schedule"
    description: "Bus Booking App"
    version: "1.0.0"
