spring:
  datasource:
    url: jdbc:postgresql://52.66.207.198:5432/postgres
    username: postgres
    password: Admin123
  config:
    import: "optional:configserver:http://localhost:8071"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  hibernate:
    ddl-auto: update

  application:
    name: busadmin

server:
  port: 8086







  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      fail-on-empty-beans: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "busadmin"
    description: "bus admin app"

build:
  version: 1.0
