spring:
  datasource:
    url: jdbc:postgresql://database-1.cxge8uw6cbp6.ap-south-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: Admin123
  config:
    import: "optional:configserver:http://localhost:8071"


  profiles:
    active: "qa"


  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  application:
    name: usermaster
  # Hibernate Configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  resources:
    static-locations: file:src/main/resources/static/



  # File upload properties
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  # Uncomment the following line if you are using reactive web application
  # main:
  #   web-application-type: reactive

server:
  port: 8090

build:
  version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,readiness,liveness
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

endpoints:
  shutdown:
    enabled: true

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     serviceUrl:
#       defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "user"
    description: "Bus Booking App"
    version: "1.0.0"
