spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/pavan6458/projectCongif.git"
          timeout: 4
          force-pull: true

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: 3mk3k3bjk3nk3bn3kh3nk3j3bj3hk3n3h3n3jfv4j4g
